### ISSUE TITLE
incorrect console error output when password is empty

### ISSUE THREAD

**Issue by Domprobst** [curious-containers/curious-containers#129]
### **Description**
**Problem**
When the value for "auth.password" is set as an empty string (""), the formatting of the console error output is incorrect. This issue occurs in the context of a Red experiment executed with a cc-agency.

**Steps to Reproduce**
1. Create a .red file with a "RedSpecificationError" error.
2. Leave the auth.password field of an red-connector-ssh empty. (not tested with other connectors)
3. Attempt to execute the experiment with a cc-agency.

**Expected Behavior**
The console error output should be properly formatted.

expected error output:
```
[RedSpecificationError]
Error while checking input key "script":
cli is declared as array, but value is not given as such
```

**Actual Behavior**
The console error output is incorrectly formatted.

actual error output:
```
[RedSpecificationError]
********E********r********r********o********r******** ********w********h********i********l********e******** ********c********h********e********c********k********i********n********g******** ********i********n********p********u********t******** ********k********e********y******** ********"********s********c********r********i********p********t********"********:********
********c********l********i******** ********i********s******** ********d********e********c********l********a********r********e********d******** ********a********s******** ********a********r********r********a********y********,******** ********b********u********t******** ********v********a********l********u********e******** ********i********s******** ********n********o********t******** ********g********i********v********e********n******** ********a********s******** ********s********u********c********h********
```

Tested with the following .red file:
```
redVersion: "9"
cli:
  cwlVersion: "v1.0"
  class: "CommandLineTool"
  baseCommand: "Rscript"
  inputs:
    script:
      type: "File[]"
      inputBinding:
        position: 0
  outputs:
    mystdout:
      type: "stdout"
    mystderr:
      type: "stderr"
  stdout: "stdout.txt"
  stderr: "stderr.txt"

inputs:
  script:
    class: "File"
    connector:
      command: "red-connector-ssh"
      access:
        host: "192.168.121.129"
        port: 22
        auth:
          username: "dominik"
          password: ""
        filePath: "~/souvemed/curious_containers/tests/input/workload.R"

outputs:
  mystdout:
    class: "stdout"
    connector:
      command: "red-connector-http"
      access:
        url: "https://encyb3haf7gch.x.pipedream.net"
  mystderr:
    class: "stderr"
    connector:
      command: "red-connector-http"
      access:
        url: "https://encyb3haf7gch.x.pipedream.net"

container:
  engine: "docker"
  settings:
    image:
      url: "dprobst/curious_containers:r_base"
    ram: 256

execution:
  engine: "ccagency"
  settings:
    access:
      url: "http://localhost:8080/"
      auth:
        username: "agency_user"
        password: "agency_password"
```
