### ISSUE TITLE
Auth Information are stored in the database

### ISSUE THREAD

**Issue by Domprobst** [curious-containers/curious-containers#153]
**Error Description**
When defining an Input as a Directory inside the red file, the connector access data will be saved in cleartext into the database.

```
inputs:
  input_dirs:
    - class: "Directory"
      connector:
        command: "red-connector-ssh"
        access:
          host: "10.0.0.50"
          port: 23
          auth:
            username: "username"
            password: "password"
          dirPath: "/data/ITS-93"
```

**Actual Behavior**
The sensitive access data is stored in clear text in the database.

**Expected Behavior**
Since the access data contains critical information like username, password or private key, it should never be stored in the database in clear text. In this case it should be masked and send to the trustee service.
